FROM ubuntu:18.04

RUN apt update && apt install -y \
        software-properties-common && \
    add-apt-repository -y ppa:lramage/sds && \
    add-apt-repository -y ppa:jnchi/ppa

RUN apt update && apt install -y \
        automake \
        autopoint \
        build-essential \
        cmake \
        curl \
        debhelper \
        devscripts \
        git \
        indent \
        libcurl4-openssl-dev \
        libjansson-dev \
        libjwt-dev \
        libsds-dev \
        libsodium-dev \
        libssl-dev \
        libtool \
        libxcrypt-dev \
        pkg-config \
        quilt

WORKDIR /usr/src/libnss_aad
COPY . /usr/src/libnss_aad
RUN tar cvzf ../libnss-aad_0.0.2.orig.tar.gz --exclude='.git*' . && \
    debuild -us -uc -i'.git' && \
    dpkg -i ../libnss-aad_0.0.2-1_amd64.deb
