FROM ubuntu:18.04

RUN apt update && apt install -y \
        automake \
        autopoint \
        build-essential \
        cmake \
        git \
        indent \
        libcurl4-openssl-dev \
        libjansson-dev \
        libjwt-dev \
        libpam0g-dev \
        libsodium-dev \
        libssl-dev \
        libtool \
        pkg-config

WORKDIR /tmp
RUN curl -Lo cjson_1.7.10.orig.tar.gz \
    https://salsa.debian.org/yanhao-guest/cJSON/-/archive/debian/1.7.10-1/cJSON-debian-1.7.10-1.tar.gz \
    && tar -xf cjson_1.7.10.orig.tar.gz && \
    cd cJSON-debian-1.7.10-1 && debuild -us -uc && \
    dpkg -i ../libcjson1_1.7.10-1_amd64.deb && \
    dpkg -i ../libcjson-dev_1.7.10-1_amd64.deb

WORKDIR /tmp
RUN curl -Lo sds_2.0.0.orig.tar.gz \
    https://gitlab.com/oxr463/sds/-/archive/debian-2.0.0-1/sds-debian-2.0.0-1.tar.gz \
    && tar -xf sds_2.0.0.orig.tar.gz && \
    mv sds-debian-2.0.0-1 sds-2.0.0 && \
    cd sds-2.0.0 && debuild -us -uc && \
    dpkg -i ../libsds2.0.0_2.0.0-1_amd64.deb && \
    dpkg -i ../libsds-dev_2.0.0-1_amd64.deb

WORKDIR /usr/src/libnss_aad
COPY . /usr/src/libnss_aad
RUN tar cvzf ../libnss-aad_0.0.2.orig.tar.gz --exclude='.git*' . && \
    debuild -us -uc -i'(.git|linux-pam)' && \
    dpkg -i ../libnss-aad_0.0.2-1_amd64.deb
